export const billingStatusLabels: Record<string, { label: string; description: string }> = {
  pending: { label: 'รอชำระ', description: 'ออก Invoice แล้วและกำลังรอผลการชำระเงิน' },
  paid: { label: 'ชำระแล้ว', description: 'บันทึกยอดชำระครบถ้วนแล้ว' },
  failed: { label: 'ชำระไม่สำเร็จ', description: 'การชำระเงินไม่สำเร็จ สามารถบันทึกผลใหม่ได้' },
  canceled: { label: 'ยกเลิกแล้ว', description: 'Invoice นี้ถูกยกเลิกและไม่สามารถรับชำระต่อได้' },
}

export function billingErrorMessage(raw: string) {
  const messages: Array<[string, string]> = [
    ['platform_admin_aal2_required', 'ต้องเข้าสู่ระบบด้วย Platform Admin และยืนยัน MFA ก่อน'],
    ['subscription_not_found', 'ไม่พบ Subscription ของ Organization นี้'],
    ['subscription_plan_version_required', 'Subscription นี้ยังไม่มี Plan Version'],
    ['active_plan_price_not_found', 'ไม่พบราคาที่เปิดใช้งานสำหรับ Plan Version นี้'],
    ['invoice_due_date_in_past', 'วันครบกำหนดต้องไม่อยู่ในอดีต'],
    ['invalid_discount_amount', 'ส่วนลดต้องไม่ติดลบและไม่เกินยอดก่อนส่วนลด'],
    ['invalid_tax_amount', 'ภาษีต้องไม่ติดลบ'],
    ['billing_reason_too_short', 'กรุณาระบุเหตุผลอย่างน้อย 3 ตัวอักษร'],
    ['invoice_not_found', 'ไม่พบ Invoice ที่เลือก'],
    ['paid_invoice_is_final', 'Invoice นี้ชำระแล้ว ไม่สามารถแก้สถานะได้'],
    ['canceled_invoice_is_final', 'Invoice นี้ยกเลิกแล้ว ไม่สามารถแก้สถานะได้'],
    ['payment_amount_must_equal_invoice_total', 'ยอดที่ชำระต้องเท่ากับยอดสุทธิของ Invoice'],
    ['gateway_requires_positive_amount', 'Payment Gateway รับเฉพาะ Invoice ที่มียอดมากกว่า 0'],
    ['payment_attempt_not_found', 'ไม่พบรายการทดสอบ Payment Gateway'],
    ['payment_attempt_is_final', 'รายการทดสอบนี้มีผลสิ้นสุดแล้ว กรุณาสร้างรายการใหม่'],
    ['sandbox_attempt_required', 'รายการนี้ไม่ใช่ Sandbox จึงไม่อนุญาตให้จำลองผล'],
    ['invalid_sandbox_result', 'ผลจำลอง Sandbox ไม่ถูกต้อง'],
    ['stripe_test_key_not_configured', 'ยังไม่ได้ตั้งค่า Stripe Test Secret Key บน Server'],
    ['stripe_test_key_required', 'ระบบอนุญาตเฉพาะ Stripe Test Secret Key เท่านั้น'],
    ['stripe_webhook_secret_not_configured', 'ยังไม่ได้ตั้งค่า Stripe Webhook Secret บน Server'],
    ['stripe_checkout_failed', 'ไม่สามารถเปิด Stripe Checkout ได้ กรุณาลองใหม่'],
    ['invalid_payment_exception_command', 'ข้อมูลคำสั่งไม่ครบ กรุณาตรวจสอบและลองใหม่'],
    ['payment_exception_command_in_progress', 'คำสั่งนี้กำลังดำเนินการ กรุณารอสักครู่'],
    ['payment_exception_action_failed', 'ไม่สามารถจัดการรายการผิดปกติได้ กรุณาตรวจสอบและลองใหม่'],
    ['payment_attempt_not_retryable', 'สถานะรายการนี้ไม่อนุญาตให้สร้าง Checkout ใหม่'],
    ['stripe_fee_not_available', 'Stripe ยังไม่ส่งค่าธรรมเนียมจริง กรุณาลองใหม่ภายหลัง'],
    ['provider_result_pending', 'Provider ยังไม่แจ้งผลสุดท้าย กรุณาตรวจสอบอีกครั้งภายหลัง'],
    ['invalid_checkout_request', 'ข้อมูลสำหรับเปิด Stripe Checkout ไม่ครบถ้วน'],
    ['invoice_not_payable', 'Invoice นี้ไม่อยู่ในสถานะที่รับชำระได้'],
    ['stripe_test_requires_positive_thb_invoice', 'Stripe Test รอบนี้รองรับ Invoice สกุล THB ที่มียอดมากกว่า 0 เท่านั้น'],
    ['stripe_test_attempt_required', 'รายการนี้ไม่ใช่ Stripe Test Mode จึงไม่สามารถตรวจค่าธรรมเนียมได้'],
    ['stripe_successful_attempt_required', 'ตรวจค่าธรรมเนียมจริงได้เฉพาะรายการที่ชำระสำเร็จแล้ว'],
    ['stripe_fee_not_available', 'Stripe ยังไม่ส่งค่าธรรมเนียมจริง กรุณารอสักครู่แล้วลองใหม่'],
    ['stripe_reconciliation_failed', 'ตรวจค่าธรรมเนียมจริงจาก Stripe ไม่สำเร็จ กรุณาลองใหม่'],
    ['billing_issuer_profile_required', 'กรุณาตั้งค่าข้อมูลผู้ออกเอกสารก่อน'],
    ['billing_customer_profile_required', 'กรุณาตั้งค่าข้อมูลผู้รับเอกสารของ Organization นี้ก่อน'],
    ['issuer_legal_name_and_address_required', 'กรุณาระบุชื่อและที่อยู่ผู้ออกเอกสารให้ครบถ้วน'],
    ['customer_legal_name_and_address_required', 'กรุณาระบุชื่อและที่อยู่ผู้รับเอกสารให้ครบถ้วน'],
    ['invoice_document_already_issued', 'Invoice นี้ออกเอกสารแล้ว'],
    ['cannot_issue_document_for_canceled_invoice', 'Invoice ที่ยกเลิกแล้วไม่สามารถออกเอกสารได้'],
    ['cancel_invoice_before_canceling_document', 'ต้องยกเลิก Invoice ต้นทางก่อนจึงจะยกเลิกเอกสารได้'],
    ['credit_note_requires_paid_invoice', 'ออก Credit Note ได้เฉพาะ Invoice ที่ชำระแล้ว'],
    ['credit_note_exceeds_invoice_total', 'ยอด Credit Note รวมต้องไม่เกินยอดเอกสาร'],
    ['invoice_document_not_issued', 'เอกสารต้นทางยังไม่อยู่ในสถานะออกเอกสาร'],
    ['transfer_channel_command_required', 'ไม่พบรหัสคำสั่ง กรุณาลองใหม่'],
    ['invalid_transfer_channel_type', 'ประเภทช่องทางรับโอนไม่ถูกต้อง'],
    ['invalid_transfer_channel_status', 'สถานะช่องทางรับโอนไม่ถูกต้อง'],
    ['transfer_channel_identity_required', 'กรุณากรอกชื่อช่องทาง ผู้ให้บริการ และชื่อบัญชีให้ครบ'],
    ['invalid_transfer_account_identifier', 'เลขบัญชีหรือหมายเลขพร้อมเพย์ต้องมีตัวเลข 6–20 หลัก'],
    ['invalid_transfer_display_order', 'ลำดับการแสดงต้องอยู่ระหว่าง 0–9999'],
    ['transfer_channel_not_found', 'ไม่พบช่องทางรับโอนที่เลือก'],
    ['transfer_channel_already_exists', 'มีเลขบัญชีหรือหมายเลขพร้อมเพย์นี้อยู่แล้ว'],
  ]
  return messages.find(([code]) => raw.includes(code))?.[1] ?? raw
}
